SystemOrganization addCategory: #'Pier-Seaside-Core'!
SystemOrganization addCategory: #'Pier-Seaside-Deprecated'!
SystemOrganization addCategory: #'Pier-Seaside-Libraries'!
SystemOrganization addCategory: #'Pier-Seaside-Magritte'!
SystemOrganization addCategory: #'Pier-Seaside-Model'!
SystemOrganization addCategory: #'Pier-Seaside-View'!
SystemOrganization addCategory: #'Pier-Seaside-Visitors'!
SystemOrganization addCategory: #'Pier-Seaside-Widgets'!
