SystemOrganization addCategory: #'Pier-Admin-Setup-ConfiguredInstances'!
SystemOrganization addCategory: #'Pier-Admin-Setup-Core'!
SystemOrganization addCategory: #'Pier-Admin-Setup-ExistingKernel'!
SystemOrganization addCategory: #'Pier-Admin-Setup-NewKernelFromDistribution'!
SystemOrganization addCategory: #'Pier-Admin-Setup-RecreateExportedKernel'!
SystemOrganization addCategory: #'Pier-Admin-UI'!
