accessing
style
	^ 'html {
	color: #111;
	font-size: 85%;
	line-height: 1.5;
	font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
}
body, table, tr, td, th {
	color: inherit;
	text-align: left;
	font-size: inherit;
	vertical-align: top;
	font-family: inherit;
}

table { margin: 1em 0; }
ul, ol { padding-left: 2em; }

code {
	padding: 2px;
	font-size: 1.2em;
	background-color: #ddd;
	-moz-border-radius: 2px;
	-webkit-border-radius: 2px;
}'