sample content
blogPostOverview
	^ (PBPost named: 'overview')
		title: 'What can Pier blogs do for me?';
		tags: #('features' 'overview');
		publication: TimeStamp now;
		contents:
'The following posts illustrate some of the powerful features available in Pier powered blogs. Some highlights:

- Feature-rich blog, including:
-- Powerful wiki syntax as well as WYSIWYG editor.
-- Tags and tag-cloud.
-- User and permission management.
-- File Uploads.
-- Bookmarkable Urls.
- Embed live Seaside components.
- Advanced support for Smalltalk code highlighting, using the same highlighter as Pharo''s code editor.
- Easy to extend and add additional pages, menu items.
- Extend with Seaside components, Pier widgets, structures and views.
- Open source, with a range a contributed add-ons available.';
		yourself