sample content
bookEntryPierAdminFeatures
	^ (BOPortion named: 'admin-features')
		type: #section;
		title: 'Pier Admin Features';
		contents:
'Pier Admin provides:
# A live preview of the site contents, synchronised with the admin UI.
# A WYSIWYG editor.
# Tree view of the site''s structure.
# From the tree view, a right click menu provides  the ability to edit nodes, add child nodes, rename nodes etc. 
# Editing uses all available space regardless of the content area defined by a site''s template.
# A configurable tabbed interface provides a convenient method for switching between views.
# Customisation via a ==/config== configurator.
# A mechanism for creating Pier sites, that requires the user to define an initial password. For security there is no default password.
# A structure for defining and sharing Pier site definitions, templates and samples (see: ==PRKernelDistributionBase==). Currently blog and book templates are defined.';
		yourself