sample content
bookEntryPierPRCommand
	^ (BOPortion named: 'PRCommand')
		type: #section;
		title: 'PRCommand';
		contents:
'
@@todo expand on the class comment below; when to use ==PRCommand== and when to use traditional Seaside ==#show:==, ==#answer:== - when kernel data is mutated. What does this mean in practice?

 ==PRCommand==''s class comment:
+value:source|class=PRCommand|comment+
';
		yourself