sample content
bookEntryAcknowledgement
	^ (BOPortion named: 'acknowledgements')
		type: #section;
		title: 'Acknowledgements';
		contents:
'Pier Admin stands on the broad shoulders of *Pier CMS>http://www.piercms.com/about*  which was created and is maintained by *Lukas Renggli>http://www.lukas-renggli.ch/*. Pier admin was conceived at a Pier sprint in Eindhoven. The participants were:
- Adriaan van Os
- Louis Andriese 
- Thomas Noordzij 
- Julian Fitzell 
- Maarten Daalder
- Norbert Hartl 
- Bart Veenstra 
- Nick Ager
- Reza Razavi
- Stephan Eggermont 
- Friso Geerlings

The book stylesheet is based on the one used by *the Moose book>http://www.themoosebook.org/book* by Tudor Girbar.

The tree widget is based on integration work by Bart Veenstra.

Pier admin was largely created by *Nick Ager>http://twitter.com/nickager*, with help from those mentioned above.';
		yourself