sample content
bookEntryPierPRWidget
	^ (BOPortion named: 'PRWidget')
		type: #section;
		title: 'PRWidget';
		contents:
'@@todo difference between ==WAComponent== and ==PRWidget== - access to the context, properties and the concept of an owner. Difference between a ==PRWidget== and a ==PRViewComponent== 

@@todo create a ''hello world'' equivalent for Pier using a ==PRWidget== derived class.

+value:source|class=PRWidget+

@@todo expand';
		yourself