sample content
bookEntryPierAdminInsidePackages
	^ (BOPortion named: 'packages')
		type: #section;
		title: 'Pier Admin''s packages ';
		contents:
'Pier Admin''s packages:
- *Seaside>http://seaside.st*.
- Pier - the base Pier classes
- Pier Addons, namely:
-- Pier-Blog 
-- Pier-Book
-- Pier-Design - allows editing of the site''s template and stylesheet.
-- Pier-Documents - Pier widget that contains a Pier document.
-- Pier-EditorEnh - Wiki editor''s toolbar and help support.
-- Pier-Google - support for *Google analytics>http://www.google.com/analytics/*
-- Pier-JQuery - jQuery widgets in Pier cycler and search
-- Pier-LinkChecker - shows all links in a document and allows them to be checked (contains bugs)
-- Pier-TagCloud - tag cloud
-- Pier-Wysiwyg - Pier WYSIWYG editor
-- Pier-FileUpload-Common-Wysiwyg
-- Pier-FileUpload-Wysiwyg - file upload support for the WYSIWYG editor
- JQWidgetBox-UILayout-Core layout allowing the left column to be collapsed
- JQWidgetBox-JSTree-Core - tree widget.';
		yourself