sample content
bookEntryPierAdminOverview
	^ (BOPortion named: 'overview')
		type: #chapter;
		title: 'Pier Admin Overview';
		contents: 'Pier Admin provides an administrative interface to *Pier>http://piercms.com*. An introduction to the interface:

{{{<iframe src="http://player.vimeo.com/video/32749535?title=0&byline=0&portrait=0&color=0" width="400" height="300" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>}}}

*value:children|link*';
		yourself