sample content
bookEntryPierPRStructure
	^ (BOPortion named: 'PRStructure')
		type: #section;
		title: 'PRStructure';
		contents:
'The ''model'' portion of Pier elements; stores the data. There are structures associated with books, book chapters, sections etc, blogs, blog entries,  pages all based on ==PRStructure==. 

 ==PRStructure==''s class comment:

+value:source|class=PRStructure|comment+

@@todo expand';
		yourself